# -*- coding: utf-8 -*-

'''

  yapa demo: setup

'''

# stdlib + setuptools
import os, setuptools


setuptools.setup(name="moments",
      version="0.1",
      author="Sam Gammon",
      packages=(
        "moments",
        "test_moments",
      ),
      scripts=["resources/moment.py"],
      tests_require=["nose"],
      author_email="sg@samgammon.com",
      description="Prototype package that generates Everalbum 'moments', which are autogenerated video slideshows.",
      url="https://github.com/sgammon/yapa-moments"
)
